### Get persons information and date timestamp
GET http://localhost:3001/info

### Unknown Endpoint
GET http://localhost:3001/unknown

### Get all people
GET http://localhost:3001/api/persons

### Get person
GET http://localhost:3001/api/persons/6a8a00b9ea2b2cc0d2cdb350

### Patch person
PATCH http://localhost:3001/api/persons/6a8a00b9ea2b2cc0d2cdb350
Content-Type: application/json

{
    "number": "000-001-7877"
}

### Delete person
DELETE http://localhost:3001/api/persons/6a8a00b9ea2b2cc0d2cdb350

### Add new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Crystal",
    "number": "555-555-5555"
}
