### Get persons information and date timestamp
GET http://localhost:3001/info

### Unknown Endpoint
GET http://localhost:3001/unknown

### Get all people
GET http://localhost:3001/api/persons

### Get person
GET http://localhost:3001/api/persons/6a873b9a1ac87a0bf1acdb70

### Patch person
PATCH http://localhost:3001/api/persons/6a873b9a1ac87a0bf1acdb70
Content-Type: application/json

{
    "number": "000-000-0000"
}

### Delete person
DELETE http://localhost:3001/api/persons/6a873b9a1ac87a0bf1acdb70

### Add new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Crystal",
    "number": "555-555-5555"
}
